# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06bc75678b016f3bbc98f1c5bab8bf62344b42824f01caf77fab4363fe47489a5c27034738fb548ee33be7afdac8455b7f7ec36f0bf38ef63103a9db5e5124ec

test:
  secret_key_base: 3b6397e778e12c90af3a4ec1c4ee65d7596f12a4a578a9eab189bd832bc018f99725f94dac71da1221b7adf3fb3dc7a17a9e366fbe8aaca034ae2d8a97858bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
